export enum DeviceCustomCommand {
  ADJUST_BRIGHTNESS = 'ADJUST_BRIGHTNESS',
  ADJUST_VOLUME = 'ADJUST_VOLUME',
  ACTIVATE_GEOFENCE = 'ACTIVATE_GEOFENCE',
  DEACTIVATE_GEOFENCE = 'DEACTIVATE_GEOFENCE',
  ACTIVATE_REMOTE_CONTROL = 'ACTIVATE_REMOTE_CONTROL',
  DEACTIVATE_REMOTE_CONTROL = 'DEACTIVATE_REMOTE_CONTROL',
}
