export enum InstallType {
  UNSPECIFIED = 'INSTALL_TYPE_UNSPECIFIED',
  PREINSTALLED = 'PREINSTALLED',
  FORCE_INSTALLED = 'FORCE_INSTALLED',
  BLOCKED = 'BLOCKED',
  AVAILABLE = 'AVAILABLE',
  REQUIRED_FOR_SETUP = 'REQUIRED_FOR_SETUP',
  KIOSK = 'KIOSK',
}
