export enum UsbDataAccess {
  UNSPECIFIED = 'USB_DATA_ACCESS_UNSPECIFIED',
  ALLOW_USB_DATA_TRANSFER = 'ALLOW_USB_DATA_TRANSFER',
  DISALLOW_USB_FILE_TRANSFER = 'DISALLOW_USB_FILE_TRANSFER',
  DISALLOW_USB_DATA_TRANSFER = 'DISALLOW_USB_DATA_TRANSFER',
}
